[package]
name = "ledgersync"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
rplaid = { version = "*", features = ["default"] }
warp = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# rust-lang/rust#78835
clap = "=3.0.0-beta.2"
futures-util = "0.3.17"
tabwriter = "1.2.1"
anyhow = "1.0.43"
chrono = "0.4.19"
dirs = "3.0.2"
pest = "2.1.3"
pest_derive = "2.1.0"
toml = "0.5.8"
