[package]
name = "ledgersync"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
rplaid = { version = "*", path = "../rplaid", features = ["default"] }
warp = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# rust-lang/rust#78835
clap = "=3.0.0-beta.2"
futures-util = "0.3.17"
tabwriter = "1.2.1"
anyhow = "1.0.43"
chrono = "0.4.19"                   # Date and time library for Rust
dirs = "3.0.2"                    # A tiny low-level library that provides platform-specific standard locations of directories fo…
pest = "2.1.3"                   # The Elegant Parser
pest_derive = "2.1.0"                # pest's derive macro
