[workspace]
members = [
  "crates/plaid_link",
]

[package]
name = "clerk"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.43"
axum = "0.5.4"
chrono = "0.4.19"
# rust-lang/rust#78835
clap = "=3.0.0-beta.2"
crossbeam-channel = "0.5.4"
dirs = "3.0.2"
futures = "0.3.17"
futures-util = "0.3.17"
http = "0.2.4"
ketos = "0.12.0"
ketos_derive = "0.12.0"
plaid-link = { path = "crates/plaid_link", version = "0.1.0" }
regex = "1.5.4"
rplaid = { version = "0.3.0", features = ["default"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.5.13", features = ["sqlite", "runtime-tokio-native-tls", "migrate"] }
tabwriter = "1.2.1"
thiserror = "1.0.31"
tokio = { version = "1", features = ["full"] }
toml = "0.5.8"
url = "2.2.2"
