name: Release
on:
  push:
    branches:
      - main
jobs:
  build_relase:
    name: 'build_release'
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          build: [linux, macos]
          include:
          - build: linux
            os: ubuntu-20.04
            rust: stable
            target: x86_64-unknown-linux-musl
          - build: macos
            os: macos-latest
            rust: stable
            target: x86_64-apple-darwin
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
          target: ${{ matrix.target }}

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --verbose

      - name: Strip release binary (linux and macos)
        if: matrix.build == 'linux' || matrix.build == 'macos'
        run: strip "target/release/ledgersync"

      - name: Archive binary
        uses: actions/upload-artifact@v1
        with:
          name: ledgersync_${{ matrix.target }}.tar.gz
          path: target/release/ledgersync
